language: node_js
sudo: true
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "4.1.2"

install:
- chromium-browser --version
- npm install -g gulp
- npm install

before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
# - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
- ./node_modules/protractor/bin/webdriver-manager update
- nohup gulp pre-tests &
script: (sleep 10; gulp e2e)
