language: node_js
sudo: required

cache:
    apt: true
    directories:
        - node_modules
        - client/assets/libs
        # - /usr/local/nvm/versions/node/v5.9.0/lib/node_modules

services:
  - docker

node_js:
  - "5.9.0"

before_install:
    - .bin/containers/build.sh
    - .bin/containers/run-db.sh -c "" -d ""
    - docker exec -it db /melhoreme/.bin/containers/scripts/wait-connection.sh
    - docker exec -d -it db gulp run 
    - docker exec -it db /melhoreme/.bin/containers/scripts/wait-server.sh 
     
before_script:
    # - export DISPLAY=:99.0
    # - sleep 2
    # - Xvfb :99.0 -extension RANDR > /dev/null &
    - docker exec -d -it db Xvfb :99.0 -extension RANDR 
    - sleep 7
    - docker exec -it db ./node_modules/protractor/bin/webdriver-manager update
    - docker exec -d -it db gulp pre-tests 

install: 
    - echo "Pronto"
script: 
    - docker exec -it db /melhoreme/.bin/containers/scripts/wait-selenium.sh 

    - docker exec -it db gulp e2e
    # - if [ $? -eq 1 ]; then exit 1; fi
    - if [ $? -eq 1 ]; then echo "fail" && exit 1; fi
    - docker exec -it db gulp test
    - if [ $? -eq 1 ]; then echo "fail" && exit 1; fi
    # - if [ $? -eq 1 ]; then exit 1; fiii
    # - gulp e2e
    # - gulp test

#soh pro push
# - sh -e /etc/init.d/xvfb start
# - docker exec -d -it db /etc/init.d/xvfb start
# - docker exec -it db export DISPLAY=:99.0
