language: node_js
sudo: false
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "4.1.2"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - ./node_modules/protractor/bin/webdriver-manager update
  - nohup gulp pre-tests &
script: (sleep 30; gulp e2e)