language: node_js
sudo: true
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - chromium-browser

node_js:
  - "4.1.2"

before_install:
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update -qq
- sudo apt-get install -qq google-chrome-stable

install:
- npm install -g gulp
- npm install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
#- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip

- ./node_modules/protractor/bin/webdriver-manager update
- nohup gulp pre-tests &
script: (sleep 10; gulp e2e)
