language: node_js
sudo: required

services:
  - docker

node_js:
  - "5.9.0"

before_install:
    # - nohup mongod &
    # - sleep 5
    # - rm -r .bin/db-backup/*
    # - mongodump --db "melhoreme-test" -o .bin/db-backup/
    # - mongodump --db "admin" -o .bin/db-backup/
    #
    # - mongod --shutdown
    - .bin/containers/clean-db.sh
    - .bin/containers/build.sh
    - .bin/containers/run-db.sh -d 
    - docker exec -it w-db /melhoreme/.bin/containers/scripts/wait-connection.sh
    - docker exec -d -it w-db gulp run
    - docker exec -it w-db /melhoreme/.bin/containers/scripts/wait-server.sh 
    - echo "Pronto" 
     
    # - docker build -f .bin/dockerfiles/db/Dockerfile -t raul010/db .
    #
    #
    # - docker build -f .bin/dockerfiles/server/Dockerfile -t raul010/server . 
    # # ./node_modules/protractor/bin/webdriver-manager update
    # - docker run --name db -d -p 127.0.0.1:27017:27017 raul010/db /bin/sh -c "nohup mongod & sleep 30; mongorestore .bin/db-backup; mongod --shutdown; sleep 5; mongod --auth"
    # # - docker exec
    # # - docker run --name db -d -p 127.0.0.1:27017:27017 raul010/db /bin/sh -c "nohup mongod & sleep 30; mongorestore .bin/db-backup"
    # - docker run --name server -d -p 127.0.0.1:8080:4567 raul010/server 
    # - docker ps -a
    # - docker logs db
    # - docker logs server
    #
# - docker run --name tests_bash -d raul010/tests /bin/bash 

# - docker exec -d tests_bash nohup mongod &
# - docker exec -d tests_bash sleep 30 &
# - docker exec -d tests_bash mongorestore .bin/db-backup &
# - docker exec -d tests_bash nohup gulp run &
# - docker exec -d tests_bash sleep 30 &
# # - docker exec -d tests_bash ./node_modules/protractor/bin/webdriver-manager update
# - docker exec -d tests_bash nohup gulp pre-tests &
# - docker exec -d tests_bash sleep 10
# - docker exec tests_bash gulp e2e 


install:
# - npm cache clean -f
# - npm config set strict-ssl false
# - npm install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
#- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
#   
# - nohup mongod &
# - mongorestore .bin/db-backup
- ./node_modules/protractor/bin/webdriver-manager update
- nohup gulp pre-tests &

script: (sleep 10; gulp e2e)

#soh pro push

