language: node_js
sudo: required

services:
  - docker

node_js:
  - "5.9.0"

before_install:
    - docker build -f .bin/dockerfiles/db/Dockerfile -t raul010/db .
    - docker build -f .bin/dockerfiles/server/Dockerfile -t raul010/server . 
    # ./node_modules/protractor/bin/webdriver-manager update
    - docker run -d -p 27017:27017 raul010/db /bin/sh -c "nohup mongod & sleep30; mongorestore .bin/db-backup"
    # - docker run raul010/tests /bin/bash -c "npm cache clean -f; npm install; nohup mongod & sleep 30; ls -lha; ls -lha .bin"
    - docker run -d -p 127.0.0.1:3000:4567 raul010/server 
    - docker ps -a

# - docker run --name tests_bash -d raul010/tests /bin/bash 

# - docker exec -d tests_bash nohup mongod &
# - docker exec -d tests_bash sleep 30 &
# - docker exec -d tests_bash mongorestore .bin/db-backup &
# - docker exec -d tests_bash nohup gulp run &
# - docker exec -d tests_bash sleep 30 &
# # - docker exec -d tests_bash ./node_modules/protractor/bin/webdriver-manager update
# - docker exec -d tests_bash nohup gulp pre-tests &
# - docker exec -d tests_bash sleep 10
# - docker exec tests_bash gulp e2e 


install:
- npm cache clean -f
- npm config set strict-ssl false
- npm install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
#- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
#   
# - nohup mongod &
# - mongorestore .bin/db-backup
- ./node_modules/protractor/bin/webdriver-manager update
- nohup gulp pre-tests &
- script: (sleep 10; gulp e2e)

#soh pro push

