language: node_js
sudo: false
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "4.1.2"

before_script:
  - npm install -g gulp
  - webdriver-manager update --standalone
  - gulp pre-tests
script: gulp e2e