language: node_js
sudo: required
env:
 - CXX=g++-4.8

addons:
  apt:
    packages:
    - g++-4.8

node_js:
- "4.1.2"

before_install:
- env
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install:
- npm install -g npm@2
- npm install -g gulp
- npm install

cache:
  directories:
  - node_modules

before_script:
- ./node_modules/protractor/bin/webdriver-manager update
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 20
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
- nohup gulp pre-tests &
script: (sleep 30; gulp e2e)
