FROM ubuntu
MAINTAINER raul@melhore.me

ENV DEBIAN_FRONTEND noninteractive

ENV PYTHON /usr/bin/python2.7

# For MongoDB
RUN echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

RUN sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list 

RUN apt-get update

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh


# to node-gyp
RUN apt-get install -y python2.7
RUN apt-get install -y build-essential --no-install-recommends

RUN apt-get install -y curl

# RUN apt-get update \
# 	&& apt-get install -y --no-install-recommends \
# 		ca-certificates \
# 		curl \
# 		wget \
# 		python2.7
# 		# build-essential \
# 		# libxss1 libappindicator1 libindicator7 xdg-utils 

# For node-gyp
#
# RUN apt-get update
#
# RUN	wget -q -O - http://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add - \                                                                                    \
# 	&& echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list \
# 	&& apt-get update
#
# RUN	apt-get install -y \
# 	google-chrome-stable
#
# #RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
# #	dpkg -i google-chrome*.deb 
#
# RUN apt-get install -y --no-install-recommends \
# 	xfonts-base \
# 	xvfb
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 5.9.0
ENV NVM_VERSION 0.31.0

# Install nvm with node and npm
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v$NVM_VERSION/install.sh | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

RUN apt-get install -y --force-yes git 

ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

 	
# RUN npm install -g gulp
#
# RUN apt-get autoremove -y \
#	&& apt-get clean -y \

ENV APP_NAME melhoreme

RUN mkdir -p /usr/src/$APP_NAME

# COPY . /usr/src/$APP_NAME

WORKDIR /usr/src/$APP_NAME

COPY package.json /usr/src/$APP_NAME/

COPY bower.json  /usr/src/$APP_NAME/

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN sudo apt-get install -y --force-yes mongodb-org

# RUN mongo --version
RUN mkdir -p /data/db
RUN chown -R `id -u` /data/db 
# ADD .bin/db-backup /db-backup
# WORKDIR /usr/src/$APP_NAME
# RUN nohup mongod &
# RUN sleep 20
# RUN mongorestore /db-backup 

# EXPOSE 8080
# EXPOSE 3000
# EXPOSE 27017

# RUN nohup mongod &
# RUN npm cache clean -f
RUN npm install -g bower
RUN npm install -g gulp
# RUN npm install -g wait-for-mongo
RUN npm config set unsafe-perm true
RUN npm config set strict-ssl false
RUN npm install
RUN npm config set unsafe-perm false
RUN npm set strict-ssl true

# RUN mongorestore .bin/db-backup

# CMD [ "gulp", "run" ]
# CMD ["mongorestore", "./db-backup"]
# CMD ["", ""]
# ENTRYPOINT ["nohup mongod &; mongorestore .bin/db-backup; nohup gulp run &; sleep 30; ./node_modules/protractor/bin/webdriver-manager update; nohup gulp pre-tests &; sleep 10; gulp e2e"]
